### ISSUE TITLE
code.tizen.org - example - Circular Index Scrollbar  indexes not displayed

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#131]
1.
Visit: https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fnavcontrols%2Findexscrollbar%2Findex.html
2. Go to live preview
3. Observe   Inexes are not displayed

**Comment by hsiwkin** [comment]
I've checked it and it's a TAU issue (independent from DE)

**Comment by wszczepanski97** [comment]
Problem of this task is that Circular Index Scrollbar can't attach indexes to itself.

First of all, in HTML file exist 2 lists, one is for taking indexes, second for carousel of listview items.
 In helper for circular index scrollbar(indexscrollbar.js) indexes are taken from first list but this list in preview mode is empty.
![list1](https://user-images.githubusercontent.com/31214439/62226393-72a1b500-b3ba-11e9-8b61-203f1b98afe2.png)
So array of indexes is empty because there are no elements in this listview. 
There are a few places where elements of listview disappear, one of them is function setAnimatedItems(), but it is not the only place.

**Comment by wszczepanski97** [comment]
I modify a ArcListview a little bit, but it still a lot to do to make IndexScrollbar works better.
My modification repairs displaying of circle with actual group index but destroy a look of widget.
For now I left this task but it still needs to be develop

**Comment by lslachciak** [comment]
@hsiwkin can we resolve this issue?

**Comment by hsiwkin** [comment]
not yet - the PR is waiting for the review. Once the PR is reviewed and merged I'll "send" this issue to a review.

**Comment by lslachciak** [comment]
indexes are now displayed

**Comment by lslachciak** [comment]
works well on
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fnavcontrols%2Findexscrollbar%2Findex.html
