### ISSUE TITLE
Box shadow property cannot be set

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU-Design-Editor#171]
In the attributes panel, there is `box-shadow` property. It is set to none by default. After changing this value there is no changing in App code, so no effect. After setting it manually in code, there is proper value but its edition has no influence to the app.
![image](https://user-images.githubusercontent.com/18300603/61459578-54c16280-a96d-11e9-9b3d-18259b14542e.png)

**Comment by hsiwkin** [comment]
I've checked it and as far as I can see this issue is no longer present on the current versions of DE. 
Regardless of that, there was an issue with the size of the input for box-shadow - it was too small so I've enlarged it. PR containing this change: https://github.com/Samsung/TAU-Design-Editor/pull/250

**Comment by lslachciak** [comment]
@korneliakobiela could you confirm that reported by you issue not longer exists?

**Comment by korneliakobiela** [comment]
Looks good, no longer exist. Thank you for fixing its size. :octopus:
