### ISSUE TITLE
Unable to delete ListView

### ISSUE THREAD

**Issue by wszczepanski97** [Samsung/TAU-Design-Editor#228]
## Technical
Platform: Both
## Description
Cannot delete saved listview from template
## Steps to reproduce
1. Create a new project in Design Editor for wearable.
2. Add listview and a few of listitems to template .
3. Save a project.
4. Delete a listview
## Expected behaviour
Listview is not displayed
## Actual behaviour
Listview moved to the top and is displayed.

**Comment by lslachciak** [comment]
@wszczepanski97 I can't reproduce this issue in the current version, could you check and attach screenshot?

**Comment by wszczepanski97** [comment]
1. Add listview with some list items
![addAListviewwithListItems](https://user-images.githubusercontent.com/31214439/62041245-79ce9480-b1fb-11e9-89d1-8bd01a7c7090.png)
2. Save a project, look of list changes a little bit.
![afterSave](https://user-images.githubusercontent.com/31214439/62041367-c619d480-b1fb-11e9-9810-0285f6cd5518.png)
3. Try to delete a listview and see that it moves up but don't disappear from project.
![afterDelete](https://user-images.githubusercontent.com/31214439/62041392-d336c380-b1fb-11e9-859d-f78fb4e6e587.png)

**Comment by korneliakobiela** [comment]
This issue occurs because there is no space, padding or sth similar between listitem and listview container. So we cannot select the whole listview, because listitem is on it. I can add padding on listview, but it changes a little whole listview width and height. I attach screenshots:
![image](https://user-images.githubusercontent.com/18300603/62717523-529a7300-ba04-11e9-979f-eabcd8a13e7a.png)
Selected whole listview
![image](https://user-images.githubusercontent.com/18300603/62717900-0865c180-ba05-11e9-9911-aa9304562a71.png)
Selected one listitem

Is this solution ok? I am not sure about the design of this component.

**Comment by korneliakobiela** [comment]
After today's meeting, I will try to find another solution which allows me to solve it. Now I will investigate what is the difference between select item itself and select using tree view.

**Comment by korneliakobiela** [comment]
Done by #282
