### ISSUE TITLE
Need to set basic configuration according to profile of project

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU-Design-Editor#288]
## Technical
VSC

## Description
In the VSC Project,  we can create the project in the WAPPL by wearable /mobile profile
When open the Design Editor, we check the profile mobile or wearable (for example config,xml ).

## Steps to reproduce
1. Create a  Wearable Project in the WAPPL of VSCode
2. Open the Design Editor

## Expected behaviour
Design Editor is open by wearable profile.

## Actual behaviour
Design Editor is open by mobile profile.

**Comment by wszczepanski97** [comment]
This issue should be solved by @hsiwkin who is change a way to set a basepath.
By default, design-editor set screen configuration to mobile and then when config.xml is found it changes screen config.
When you open index.html but in upper directory, basepath is upper directory and design-editor is looking for config.xml in this upper directory instead of project directory. 
config.xml is not found and screen config is not changed.

**Comment by hsiwkin** [comment]
I've reproduced the steps described above and now - after merging the fixes regarding opening projects in workspaces - the issue does not occur.

**Comment by singa2000** [comment]
It's good working.
We can be close the issue
