### ISSUE TITLE
Audio component not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#333]
## Technical
Audio component not working

## Steps to reproduce
1. Open a  project in Design Editor (VSC)
2. D&D Audio component
3. Click Audio component
4. Attributes->Audio Src, choose some file
e.g. from site: https://file-examples.com/index.php/sample-audio-files/
5. Click live preview
6. Observe

## Expected behaviour
Audio file played after clicking play. Play progress visible
## Actual behaviour
Audio not played
No progress visible

**Comment by wszczepanski97** [comment]
I found a problem with using audio/video files in webview 
https://github.com/Microsoft/vscode/issues/54097
As you can read. audio/video codecs in most of the cases are not supported.

**Comment by lslachciak** [comment]
threy don't support ffmpeg compressions. but uncompressed wave should be supported I think

**Comment by wszczepanski97** [comment]
I checked which kind of music file extensions are supported and works in VSC.
They are .aac and .flac files. 
I will add a validation which allow to add only this type of music files.

**Comment by singa2000** [comment]
In  my test,  mp4 file is working and progress is visible.

**Comment by lslachciak** [comment]
@singa2000 mp4 is video format and I think it is supported. I didn't note any issues with video files.
 I reported issue for audio component with audio files

**Comment by wszczepanski97** [comment]
The problem is more complex.
First of all, files such as video and music were added as a blob - reference to the file on the disk.
**We need to add video, audio to project** because then if somebody wants to launch a project on other PC and the file with audio, video is not on this PC, it is not possibility to load video or audio.
I take care of this and do it in a few steps:
1. Create solution to add audio, video to project
2. Set relative path to panel "element"(if needed)
3. Create a validation for only adding working files in VSCode

**Comment by lslachciak** [comment]
@wszczepanski97 let's separate additional problems
2. Create solution to add audio, video to project
3. Set relative path to panel "element"(if needed)
int new issue.

This issue is for problem in local test, not test on device so relative paths doesn't matter here.

**Comment by wszczepanski97** [comment]
PR is merged, @lslachciak please check is everything works good.

**Comment by lslachciak** [comment]
works good, only supported files can be chosen
