### ISSUE TITLE
[Wearable] [VSCode] Checkbox/radio widget when selected are not filled in

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#340]
## Technical
[Wearable] [VSCode] Checkbox/radio widget when selected are not filled in
## Steps to reproduce
1. Open sampleproject in Design Editor
2. D&D checkbox widget
3. Go to Live Preview
4. Click on the checbox widget
## Expected behaviour
Checkbox is marked
## Actual behaviour
Checkbox is not marked
![image](https://user-images.githubusercontent.com/2246331/64528925-f16b0580-d309-11e9-93d7-aecaac7e5f43.png)
[W Sample TAU 1.1.4.zip](https://github.com/Samsung/TAU-Design-Editor/files/3590330/W.Sample.TAU.1.1.4.zip)

**Comment by hsiwkin** [comment]
From I can see the problem occurs due to the fact that the image needed for the checkbox component is not copied to the project directory. 
I'll investigate it and try to fix it tomorrow.

**Comment by hsiwkin** [comment]
I've found the root of this issue. 
It's because we have wrong link in tau.circle (which is because we have both tau catalogue that contains tau.circle and tau.circle itself copied alone - without files it's referring to). 
It should work without this lone double tau.circle. 

We probably should restrict conditions under which we copy libs like tau.circle to projects directory.

**Comment by hsiwkin** [comment]
BTW I've also fixed error caused by _setIcon in component-element and added several tests while working on this case : )

**Comment by hsiwkin** [comment]
thanks to #358 paths now works fine :

**Comment by lslachciak** [comment]
works fine
