### ISSUE TITLE
(Wearable) Section changer is not adding sections properly

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU-Design-Editor#346]
## Technical
Section changer is not adding sections

1. Open wearable project in DE
2. Add Section changer
3. Click on section
4. Click on the + button add add few sections
5. Go to live preview

## Expected behaviour
Sections are change with mouse scroll
## Actual behaviour
All sections visible at once
![image](https://user-images.githubusercontent.com/2246331/64533102-1e6fe600-d313-11e9-88db-48a3aae098f3.png)

**Comment by grzegorz-czajkowski** [comment]
Different behavior with https://github.com/Samsung/TAU/pull/423.
Assuming SectionChanger is not resized, none section is displayed.
If SectionChanger is resized. Section appears properly in preview (can be scrolled).

**Comment by grzegorz-czajkowski** [comment]
There are two issues related with this bug:
 - section changer height initial value in Preview is smaller than its size in DE mode
 - section changer height become 0 after this line:
```
utilsObject.inherit(SectionChanger, Scroller, {
   ...
   self.scroller.style.position = "absolute";
}
```

**Comment by grzegorz-czajkowski** [comment]
Please ignore comment above. I was using Mobile profile for TAU due to my work on https://github.com/Samsung/TAU-Design-Editor/issues/380.

Issue is that sectionchanger has no required styles,  crucial attributes are missed like 'id', 'data-tau-built' etc which results in no proper initialization of scroller within sectionchanger.
On Mobile SectionChanger() function is called while going to Preview, callstack:
```
SectionChanger (tau.js:24200)
processWidget (tau.js:3297)
processHollowWidget (tau.js:3428)
processBuildQueueItem (tau.js:3465)
createWidgets (tau.js:3521)
prototype.change (tau.js:14590)
routePage.open (tau.js:53020)
resolve (tau.js:15443)
Router._openDeferred (tau.js:15457)
Router.open (tau.js:15512)
Router.register (tau.js:15852)
Router.init (tau.js:15628)
(anonymous) (tau.js:16293)
trigger (tau.js:1545)
build (tau.js:3585)
(anonymous) (tau.js:1869)
```
whereas on Wearable it's not called.

**Comment by grzegorz-czajkowski** [comment]
Patch merged.
